@startuml
agent browser

node "server" {
    component nginx:80 as nc {
    }
    component client as cc {
    }
    component server as sc {
    }
    component db as dc {
    }
}

browser -> server#green: server:80/
server -do-> nc#green: :80/

nc -do-> cc#green :client:1234/


browser -> server: server:80/todo
server -do-> nc: :/todo

nc -do-> sc :server:4567/todo
sc -do-> dc :db:3306




@enduml
