name: E2E Test (Selenium Webdriver)

on: [pull_request]
#on: [release]


jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      - name: Clone API server from ibwgr/todomvc-server
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'ibwgr'
          repository: 'todomvc-server'

      - name: Start API server
        run: |
          cd todomvc-server
          npm ci
          npm run start &

      - name: NPM install CI
        run: npm ci
      - name: Start app
        run: npm run start:ci &
        env:
          API_SERVER_URL: http://localhost:3100
      - name: Run test
        run: npm test
        env:
          CI: true
